// Export sheet data to JSON via this method and paste below.
// https://benborgers.com/posts/google-sheets-json
// https://opensheet.elk.sh/1KjWh96EXw8-lf8c-MvMb802Wqp8oOlF8ahYRVKxkcWE/Sheet1

export default [
  {
    fileName: 'theWave_photo',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'quilt|personal|political|analog',
    qualityRating: '9',
    title: 'The Wave',
    URL: '',
    description:
      'In 2016 a wave of progressive ideals–spearheaded by Bernie Sanders, a figurehead who was portentiously visited by a small finch which came and sat on the podium during a speech in Oregon–crashed down into confusion and chaos. Amid the helplessness of that years end, it was vital to remeber that when a wave crashes down in froth and flare, it’s energy is not lost, merely transferred under the water to take on a new form, and rise again.',
  },
  {
    fileName: 'kidDandelionFall',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'digital|vector|children|digital',
    qualityRating: '9',
    title: 'Fall Winds',
  },
  {
    fileName: 'cookieMonster_poster',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'charcoal|graphite|analog',
    qualityRating: '8',
    title: 'The Mystery Of Sidney Monster',
    URL: '',
    description:
      'He lowered the glass of milk slowly to the table. It seemed they had caught up with him at last. \n(Cookie Monster depicted as a mystery in the Mysteries of Harris Burdick), charcoal and graphite',
  },
  {
    fileName: 'partwayToWinter',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'laser|watercolor|woodCut|personal|analog',
    qualityRating: '8',
    title: 'Partway to Winter',
    URL: '',
    description: 'woodcut and watercolor',
  },
  {
    fileName: 'tithonia',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'watercolor|nature|analog',
    qualityRating: '8',
    title: 'Tithonia',
    URL: '',
    description: 'Osmia visits Tithonia at sunset, watercolor',
  },
  {
    fileName: 'wibbeldywobbldy',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'acrylics|nerdy||analog',
    qualityRating: '8',
    title: 'Wibbeldy Wobbledy',
    URL: '',
    description: 'acrylic on canvas',
  },
  {
    fileName: 'giraffe',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'digital|portrait|digital',
    qualityRating: '8',
    title: 'Giraffe',
  },
  {
    fileName: 'nightTrain',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'digital|illustration|children|digital',
    qualityRating: '8',
    title: 'The Night Train ',
    URL: '',
    description: 'Childrens Literature Concept Illustration',
  },
  {
    fileName: 'transformation_step_01',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'sketch|exercise|graphite|analog',
    qualityRating: '7',
    title: 'Transformation',
    URL: '',
    description: 'Animation Sketching Exercise, graphite',
    dateCreated: '',
    projectMembership: 'transformation',
  },
  {
    fileName: 'transformation_step_02',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'sketch|exercise|graphite|analog',
    qualityRating: '7',
    title: 'Transformation',
    URL: '',
    description: 'Animation Sketching Exercise, graphite',
    dateCreated: '',
    projectMembership: 'transformation',
  },
  {
    fileName: 'transformation_step_03',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'sketch|exercise|graphite|analog',
    qualityRating: '7',
    title: 'Transformation',
    URL: '',
    description: 'Animation Sketching Exercise, graphite',
    dateCreated: '',
    projectMembership: 'transformation',
  },
  {
    fileName: 'transformation_step_04',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'sketch|exercise|graphite|analog',
    qualityRating: '7',
    title: 'Transformation',
    URL: '',
    description: 'Animation Sketching Exercise, graphite',
    dateCreated: '',
    projectMembership: 'transformation',
  },
  {
    fileName: 'transformation_step_05',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'sketch|exercise|graphite|analog',
    qualityRating: '7',
    title: 'Transformation',
    URL: '',
    description: 'Animation Sketching Exercise, graphite',
    dateCreated: '',
    projectMembership: 'transformation',
  },
  {
    fileName: 'hazelnuts',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'chalkPastel|analog',
    qualityRating: '7',
    title: 'Hazelnuts',
    URL: '',
    description: 'chalk pastel',
  },
  {
    fileName: 'imagine01_poster',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'digital|vector|digital',
    qualityRating: '7',
    title: 'Imagine',
    URL: '',
    description:
      'Received “Clients Pick” award at Media arts student show, 2013\r',
  },
  {
    fileName: 'resolution',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'digital|personal|motherhood|digital',
    qualityRating: '7',
    title: 'Resolution',
    URL: '',
    description:
      "As the ordeal of birth fades from the forefront, and the chaos and novelty of a newly formed family begins to subside, motherhood takes shape, and a tiny human resolves out of the rippling dots of the sickbed's all too familar pillows",
  },
  {
    fileName: 'wateringKid',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'digital|personal|motherhood|digital',
    qualityRating: '7',
    title: 'Watering',
    URL: '',
    description: 'digital painting',
  },
  {
    fileName: 'toucan',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'digital|illustration|digital',
    qualityRating: '6',
    title: 'Toucan',
    URL: '',
    description: 'Surface Design Concept',
    dateCreated: '',
    projectMembership: 'transformation',
  },
  {
    fileName: 'pisgahSilo',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'watercolor|fieldSketch|analog',
    qualityRating: '6',
    title: 'Pisgah Silo',
    URL: '',
    description: 'watercolor field sketch',
  },
  {
    fileName: 'woodTrain',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'sketch|exercise|ink|analog',
    qualityRating: '6',
    title: 'Wooden Train',
    URL: '',
    description: 'ink',
  },
  {
    fileName: 'bird',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'card|digitalPainting|digital',
    qualityRating: '6',
    title: 'Nesting',
  },
  {
    fileName: 'daniel',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'digital|portrait|digital',
    qualityRating: '6',
    title: 'Portrait',
  },
  {
    fileName: 'oregonBoat',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'digital|illustration|digital',
    qualityRating: '6',
    title: 'Boat',
    URL: '',
    description: 'Mckenzie river view, digital painting',
  },
  {
    fileName: 'foxHatKid',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: 'digital|portrait|digital',
    qualityRating: '5',
    title: 'Portrait',
  },
  {
    fileName: 'the_many_faced_god',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'fine',
    tags: '',
    qualityRating: '',
    title: '',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: '',
    active: 'FALSE',
  },
  {
    fileName: 'artAtLane_flyer',
    fileNameS: 'artAtLane_flyer_s.jpg',
    fileNameM: 'artAtLane_flyer_s.jpg',
    fileNameLG: 'artAtLane_flyer_s.jpg',
    fileNameXL: 'artAtLane_flyer_s.jpg',
    filetype: '',
    category: 'gd',
    tags: 'DMC|artAtLane|internshipWork|original|promotional',
    qualityRating: '4',
    title: 'Annual High School Juried Art Exhibit',
    URL: '',
    description:
      'Flyer produced and designed with original artwork for event at Lane Community College',
    dateCreated: '',
    projectMembership: 'artAtLane',
    active: 'FALSE',
  },
  {
    fileName: 'costanoa_web',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'costanoa|physical|mockup|resort|studentWork|packaging|branding',
    qualityRating: '4',
    title: 'Costanoa Eco Resort Stationary Set',
    URL: '',
    description: 'Part of a full rebrand of Costanoa eco-resort',
    dateCreated: '',
    projectMembership: 'costanoa',
    active: 'FALSE',
  },
  {
    fileName: 'artAtLane_Flyers',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'DMC|artAtLane|internshipWork|mockup|promotional',
    qualityRating: '10',
    title: 'LCC Art Student Invitational',
    URL: '',
    description:
      'Flyer produced and designed with original artwork for event at Lane Community College',
    dateCreated: '',
    projectMembership: 'artAtLane',
    active: 'TRUE',
  },
  {
    fileName: 'CS15_poster',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'CS15|print|poster|mockup|event|studentWork|branding',
    qualityRating: '10',
    title: 'CS15 Event Posters',
    URL: '',
    description:
      'The CS15 project consisted of branding of an international conference on art and technology in a two week turnaround. Logo, Poster, & art direction are my personal work as part of an overall team of four designers. Conceptual framework for the art direction attempts to merge technologial visuals with the organic & artistic.',
    dateCreated: '',
    projectMembership: 'cs15',
    active: 'TRUE',
  },
  {
    fileName: 'costanoa_gin',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'costanoa|physical|mockup|resort|studentWork|packaging|branding',
    qualityRating: '9',
    title: 'Costanoa Eco Resort Branded Gin',
    URL: '',
    description:
      'Part of a full rebrand of Costanoa eco-resort, including expanding the brand to products both related and not directly related to the operations of the facility ',
    dateCreated: '',
    projectMembership: 'costanoa',
    active: 'TRUE',
  },
  {
    fileName: 'teaBoxes_stagedPhoto',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'edenOrganicsTea|staged|packaging|studentWork|box|red|green|grey|blue|packaging',
    qualityRating: '9',
    title: 'Eden Organics Tea Boxes',
    URL: '',
    description:
      'Four tea box set packaging design for Eden Organics with existing company logo',
    dateCreated: '',
    projectMembership: 'edenOrganics',
    active: 'TRUE',
  },
  {
    fileName: 'edenOrganicsTea_earlGrey',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'edenOrganicsTea|staged|packaging|studentWork|box|red|green|grey|blue|packaging',
    qualityRating: '9',
    title: 'Eden Organics Earl Grey Box Face',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'edenOrganics',
    active: 'TRUE',
  },
  {
    fileName: 'edenOrganicsTea_greenTea_dieline',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'edenOrganicsTea|staged|packaging|studentWork|box|red|green|grey|blue|packaging',
    qualityRating: '9',
    title: 'Eden Organics Green Tea Dieline',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'edenOrganics',
    active: 'TRUE',
  },
  {
    fileName: 'edenOrganicsTea_nightTime',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'edenOrganicsTea|staged|packaging|studentWork|box|red|green|grey|blue',
    qualityRating: '9',
    title: 'Eden Organics Night Time Tea Box Face',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'edenOrganics',
    active: 'TRUE',
  },
  {
    fileName: 'edenOrganicsTea_oolong',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'edenOrganicsTea|staged|packaging|studentWork|box|red|green|grey|blue',
    qualityRating: '9',
    title: 'Eden Organics Oolong Tea Box Face',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'edenOrganics',
    active: 'TRUE',
  },
  {
    fileName: 'mirage_cover',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'mirage|magazine|mockup|studentWork|editorial',
    qualityRating: '9',
    title: 'Mirage Magazine: Exterior',
    URL: '',
    description:
      'Photography Magazine design work, front and back cover, advertisement and 6-page article layout on the Photographic work of artist Ziqian Liu. Text written by Devid Gualandris.',
    dateCreated: '',
    projectMembership: 'mirage',
    active: 'TRUE',
  },
  {
    fileName: 'staunton_fall_11x17',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'staunton|print|poster|mockup|event|studentWork|branding|branding',
    qualityRating: '9',
    title: 'Staunton Classical Music Festival Poster: Fall',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'staunton',
    active: 'TRUE',
  },
  {
    fileName: 'staunton_summer_11x17',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'staunton|print|poster|mockup|event|studentWork|branding|branding',
    qualityRating: '9',
    title: 'Staunton Classical Music Festival Poster: Summer',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'staunton',
    active: 'TRUE',
  },
  {
    fileName: 'theBleed_summary_mockup',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'theBleed|communicacion|mockup|studentWork|editorial',
    qualityRating: '9',
    title: 'The Bleed Magazine',
    URL: '',
    description:
      'Art direction, writing, editing, illustration and graphic design for The Bleed Magazine, a national-award-winning Magazine on  Art & Design. ',
    dateCreated: '',
    projectMembership: 'theBleed',
    active: 'TRUE',
  },
  {
    fileName: 'theBleed_communicacion_mockup',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'theBleed|communicacion|mockup|studentWork|editorial',
    qualityRating: '9',
    title: 'An Act of Communicación',
    URL: '',
    description:
      'Magazine spread I co-wrote and designed, exploring, both textually and visually, the challenges of adapting content for bilingual audiences and communicating visually across cultures',
    dateCreated: '',
    projectMembership: 'theBleed',
    active: 'TRUE',
  },
  {
    fileName: 'bothAlarmAndHope_spread',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'theBleed|alarmHope|mockup|studentWork|editorial',
    qualityRating: '9',
    title: 'Both Alarm & Hope',
    URL: '',
    description:
      'Magazine spread I designed and wrote about the challenges of creating art and design that communicates effectively about climate change.',
    dateCreated: '',
    projectMembership: 'theBleed',
    active: 'TRUE',
  },
  {
    fileName: 'SNF_mockup',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'web|professional|mockup|green|blue|yellow|local|naturalFoods',
    qualityRating: '9',
    title: 'Sundance Natrual Foods Website Design',
    URL: 'https://sundancenaturalfoods.com/',
    description:
      'Worked with local web development company Wagon Wheel Web (development) to produce a full redesigned website with a backend for local natural foods insitution Sundance Natural Foods',
    dateCreated: '',
    projectMembership: 'sundance',
    active: 'TRUE',
  },
  {
    fileName: 'sundanceWine',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'web|professional|mockup|green|red|yellow|local|naturalFoods',
    qualityRating: '9',
    title: 'Sundance Wine Cellars Website',
    URL: 'http://www.orwines.com/',
    description:
      'Full design and development of local wine merchant Sundance Wine Cellars/Oregon Wine Merchants website',
    dateCreated: '',
    projectMembership: 'sundance',
    active: 'TRUE',
  },
  {
    fileName: 'artAtLane_flyerMockup',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'DMC|artAtLane|mockup|internshipWork|promotional',
    qualityRating: '8',
    title: 'Annual High School Juried Art Exhibit',
    URL: '',
    description:
      'Flyer produced and designed with original artwork for event at Lane Community College',
    dateCreated: '04/2022',
    projectMembership: 'artAtLane',
    active: 'TRUE',
  },
  {
    fileName: 'kenKwapis_flyer_mockup',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'DMC|kenKwapis|internshipWork|mockup|promotional',
    qualityRating: '8',
    title: 'Ken Kwapis Visiting Artist Event',
    URL: '',
    description:
      'Flyer produced and designed for visiting artist event at Lane Community College',
    dateCreated: '',
    projectMembership: 'artAtLane',
    active: 'TRUE',
  },
  {
    fileName: 'costanoa_cosmetics',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'costanoa|physical|mockup|resort|studentWork|branding',
    qualityRating: '8',
    title: 'Costanoa Eco Resort Cosmetics',
    URL: '',
    description:
      'Part of a full rebrand of Costanoa eco-resort, including expanding the brand to products both related and not directly related to the operations of the facility ',
    dateCreated: '',
    projectMembership: 'costanoa',
    active: 'TRUE',
  },
  {
    fileName: 'costanoa_stationary',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'costanoa|stationary|resort|studentWork|brandedProduct|branding',
    qualityRating: '8',
    title: 'Costanoa Eco Resort Stationary Set',
    URL: '',
    description: 'Part of a full rebrand of Costanoa eco-resort',
    dateCreated: '',
    projectMembership: 'costanoa',
    active: 'TRUE',
  },
  {
    fileName: 'costanoa_tea',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'costanoa|physical|mockup|resort|studentWork|packaging|brandedProduct|branding',
    qualityRating: '8',
    title: 'Costanoa Eco Resort Stationary Set',
    URL: '',
    description: 'Part of a full rebrand of Costanoa eco-resort',
    dateCreated: '',
    projectMembership: 'costanoa',
    active: 'TRUE',
  },
  {
    fileName: 'CS15_program_01',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'CS15|print|program|mockup|event|studentWork|branding',
    qualityRating: '8',
    title: 'CS15 Event Program',
    URL: '',
    description: 'Program was required to be 8-pages, 2 colors, no bleed.  ',
    dateCreated: '',
    projectMembership: 'cs15',
    active: 'TRUE',
  },
  {
    fileName: 'CS15_web_mockup',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'CS15|web|program|mockup|event|studentWork',
    qualityRating: '8',
    title: 'CS15 Event Web Page',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'cs15',
    active: 'TRUE',
  },
  {
    fileName: 'mirage_firstSpread',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'mirage|magazine|mockup|studentWork|editorial',
    qualityRating: '8',
    title: 'Mirage Magazine: First Spread',
    URL: '',
    description:
      'Photography Magazine design work, front and back cover, advertisement and 6-page article layout on the Photographic work of artist Ziqian Liu. Text written by Devid Gualandris.',
    dateCreated: '',
    projectMembership: 'mirage',
    active: 'TRUE',
  },
  {
    fileName: 'staunton_allSeasons_posters',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'staunton|print|poster|mockup|event|studentWork|branding|branding',
    qualityRating: '8',
    title: 'Three Seasons of Staunton',
    URL: '',
    description:
      'Branding for Contemporary and Historical Classical Music Festival in Staunton Virginia, spring 2022. Multi-Season cohesive but differentiated promotional materials.',
    dateCreated: '',
    projectMembership: 'staunton',
    active: 'TRUE',
  },
  {
    fileName: 'staunton_roadBanner',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'staunton|print|promotional|mockup|event|studentWork|branding',
    qualityRating: '8',
    title: 'Staunton Classical Music Festival Road Banner: Summer',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'staunton',
    active: 'TRUE',
  },
  {
    fileName: 'staunton_tickets',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'staunton|print|poster|mockup|event|studentWork|tickets|branding',
    qualityRating: '8',
    title: 'Staunton Classical Music Festival Poster: Summer',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'staunton',
    active: 'TRUE',
  },
  {
    fileName: 'artAtLane02_insta',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'DMC|artAtLane|internshipWork|mockup|promotional',
    qualityRating: '7',
    title: 'LCC Art Student Invitational',
    URL: '',
    description:
      'Promotional flyer adapted to instagram for event at Lane Community College',
    dateCreated: '',
    projectMembership: 'artAtLane',
    active: 'TRUE',
  },
  {
    fileName: 'costanoa_business_card',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'costanoa|businessCard|stationary|resort|studentWork|branding',
    qualityRating: '7',
    title: 'Costanoa Eco Resort Business Card',
    URL: '',
    description: 'Part of a full rebrand of Costanoa eco-resort',
    dateCreated: '',
    projectMembership: 'costanoa',
    active: 'TRUE',
  },
  {
    fileName: 'costanoa_mug',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'costanoa|physical|mockup|resort|studentWork|packaging|brandedProduct|branding',
    qualityRating: '7',
    title: 'Costanoa Eco Resort Branded Camping Mug',
    URL: '',
    description:
      'Part of a full rebrand of Costanoa eco-resort, including expanding the brand to products both related and not directly related to the operations of the facility ',
    dateCreated: '',
    projectMembership: 'costanoa',
    active: 'TRUE',
  },
  {
    fileName: 'costanoa_tote',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'costanoa|physical|mockup|resort|studentWork|packaging|brandedProduct|branding',
    qualityRating: '7',
    title: 'Costanoa Eco Resort Stationary Set',
    URL: '',
    description: 'Part of a full rebrand of Costanoa eco-resort',
    dateCreated: '',
    projectMembership: 'costanoa',
    active: 'TRUE',
  },
  {
    fileName: 'mirage_secondSpread',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'mirage|magazine|mockup|studentWork|editorial',
    qualityRating: '7',
    title: 'Mirage Magazine: Second Spread',
    URL: '',
    description:
      'Photography Magazine design work, front and back cover, advertisement and 6-page article layout on the Photographic work of artist Ziqian Liu. Text written by Devid Gualandris.',
    dateCreated: '',
    projectMembership: 'mirage',
    active: 'TRUE',
  },
  {
    fileName: 'staunton_wine',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'staunton|mockup|event|studentWork|tickets|brandedProduct|branding|branding',
    qualityRating: '7',
    title: 'Staunton Classical Music Festival Branded Wine',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'staunton',
    active: 'TRUE',
  },
  {
    fileName: 'staunton_tshirt',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'staunton|mockup|event|studentWork|tickets|brandedProduct|branding|branding',
    qualityRating: '7',
    title: 'Staunton Classical Music Festival Shirt',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'staunton',
    active: 'TRUE',
  },
  {
    fileName: 'phobiaIllustration_layout',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'illustration|physicalMedia|black|white|noColor|scratchboard|magazine|mockup|studentWork|illustration',
    qualityRating: '7',
    title: 'Nightmare Bear and Trypophobic Lotus',
    URL: '',
    description:
      'Illustration for Things to Fear and Loathe, an article in the Opinonator on phobias, Scratchboard',
    dateCreated: '',
    projectMembership: '',
    active: 'TRUE',
  },
  {
    fileName: 'costanoa_notebook',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'costanoa|physical|mockup|stationary|resort|studentWork|packaging|brandedProduct|branding',
    qualityRating: '6',
    title: 'Costanoa Eco Resort Branded Notepad',
    URL: '',
    description:
      'Part of a full rebrand of Costanoa eco-resort, including expanding the brand to products both related and not directly related to the operations of the facility ',
    dateCreated: '',
    projectMembership: 'costanoa',
    active: 'TRUE',
  },
  {
    fileName: 'CS15_H20mockup',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'CS15|physical|mockup|event|studentWork|brandedProduct|branding',
    qualityRating: '6',
    title: 'CS15 Reusable Water Bottle',
    URL: '',
    description: 'Part of CS15 Event Brand',
    dateCreated: '',
    projectMembership: 'cs15',
    active: 'TRUE',
  },
  {
    fileName: 'CS15_mask',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'CS15|physical|mockup|event|studentWork|brandedProduct|branding',
    qualityRating: '6',
    title: 'CS15 Face Mask',
    URL: '',
    description: 'Part of CS15 Event Brand',
    dateCreated: '',
    projectMembership: 'cs15',
    active: 'TRUE',
  },
  {
    fileName: 'mirage_thirdSpread',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'mirage|magazine|mockup|studentWork|editorial',
    qualityRating: '6',
    title: 'Mirage Magazine: Third Spread',
    URL: '',
    description:
      'Photography Magazine design work, front and back cover, advertisement and 6-page article layout on the Photographic work of artist Ziqian Liu. Text written by Devid Gualandris.',
    dateCreated: '',
    projectMembership: 'mirage',
    active: 'TRUE',
  },
  {
    fileName: 'staunton_umbrella',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'staunton|mockup|event|studentWork|tickets|brandedProduct|branding',
    qualityRating: '6',
    title: 'Staunton Classical Music Festival Umbrella',
    URL: '',
    description: '',
    dateCreated: '',
    projectMembership: 'staunton',
    active: 'TRUE',
  },
  {
    fileName: 'kenKwapis_flyer',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'DMC|kenKwapis|internshipWork|promotional',
    qualityRating: '5',
    title: 'Ken Kwapis Visiting Artist Event',
    URL: '',
    description:
      'Flyer produced and designed for visiting artist event at Lane Community College',
    dateCreated: '',
    projectMembership: 'cs15',
    active: 'TRUE',
  },
  {
    fileName: 'CS15_badge_mokcup',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'CS15|physical|mockup|event|studentWork|packaging|branding',
    qualityRating: '4',
    title: 'CS15 Staff Badge',
    URL: '',
    description: 'Part of CS15 Event Brand',
    dateCreated: '',
    projectMembership: 'cs15',
    active: 'TRUE',
  },
  {
    fileName: 'artAtLane_insta',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'DMC|artAtLane|internshipWork|mockup|promotional',
    qualityRating: '7',
    title: 'Annual High School Juried Art Exhibit',
    URL: '',
    description:
      'Promotional flyer adapted to instagram for event at Lane Community College',
    dateCreated: '',
    projectMembership: 'artAtLane',
  },
  {
    fileName: 'pedalers_flyer_wilson',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'gd',
    tags: 'advertisement|studentWork|blue|local|',
  },
  {
    fileName: 'aa_7736',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_7741',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_1364',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_0000',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_0300',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_0301',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_0306',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_0716',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
    qualityRating: '',
    title: 'Rights',
  },
  {
    fileName: 'aa_1578',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
    qualityRating: '',
    title: 'The Hanging Man',
  },
  {
    fileName: 'aa_1709',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
    qualityRating: '',
    title: 'No Logs',
  },
  {
    fileName: 'aa_1737',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_1782',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_1907',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
    qualityRating: '',
    title: 'Regrowth',
  },
  {
    fileName: 'aa_1961',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
    qualityRating: '',
    title: 'The Way',
  },
  {
    fileName: 'aa_2075',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_2114',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_2183',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_4912',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_6694',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_7425',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_7452',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'aa_97050',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'abstract',
  },
  {
    fileName: 'art_0000',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_0002',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_1364',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_1578',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_2881',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_3150',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_6228',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_6248',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_7082',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_7287',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_7293',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_7303',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_7394',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_7403',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_7487',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_7817',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_7833',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_7839',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_7859',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_8098',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_8114',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_8138',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_8642',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_8665',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'art_8672',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'fineArt',
  },
  {
    fileName: 'nature_141932',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_1613',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_2183',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_2473',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_2490',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_2934',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_2980',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_3016',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_3237',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_33811',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_3681',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_3810',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_3836',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_3862',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_3902',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_39778',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_4017',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_4044',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_4052',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_4620',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_4997',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_5281',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_56357',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_57240',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_6006',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_7061',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_7679',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_7724',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_8440',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_8668',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_8703',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_8715',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_8819',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_9039',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_9069',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_9081',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_9314',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_9372',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_9524',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'nature_97050',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'nature',
  },
  {
    fileName: 'portraits_0000',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: 'portraits_1002',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: 'portraits_1004',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: 'portraits_1633',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: 'portraits_1642',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: 'portraits_1770',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: 'portraits_1903',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: 'portraits_1916',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: 'portraits_8612',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: 'portraits_8740',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: 'portraits_8757',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: 'portraits_8782',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
    tags: 'portrait',
  },
  {
    fileName: '141932_photography',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: '33811_photography',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: '39778_photography',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: '5281_photography',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: '6006_photography',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: '7679_photography',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: '7724_photography',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: '8715_photography',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: '8819_photography',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: '9039_photography',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: 'full_size_photo_optimized45',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: 'full_size_photo_optimized57',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: 'photo',
  },
  {
    fileName: 'CS15_program_02',
    fileNameS: '',
    fileNameM: '',
    fileNameLG: '',
    fileNameXL: '',
    filetype: '',
    category: '',
    tags: 'CS15|print|program|mockup|event|studentWork',
    qualityRating: '7',
    title: 'CS15 Event Program',
    URL: '',
    description: 'Program was required to be 8-pages, 2 colors, no bleed.  ',
    dateCreated: '',
    projectMembership: 'cs15',
    active: 'TRUE',
  },
  {},
  {},
  {},
  {
    fileName: 'socialSceince_logo_onDark',
    fileNameS: 'MISSING',
    fileNameM: 'MISSING',
    fileNameLG: 'MISSING',
    fileNameXL: 'MISSING',
  },
  {
    fileName: 'socialSceince_logo_onLight',
    fileNameS: 'MISSING',
    fileNameM: 'MISSING',
    fileNameLG: 'MISSING',
    fileNameXL: 'MISSING',
  },
  {
    fileName: 'STEM_logo_darkBkg',
    fileNameS: 'MISSING',
    fileNameM: 'MISSING',
    fileNameLG: 'MISSING',
    fileNameXL: 'MISSING',
  },
  {
    fileName: 'STEM_logo_lightBkg',
    fileNameS: 'MISSING',
    fileNameM: 'MISSING',
    fileNameLG: 'MISSING',
    fileNameXL: 'MISSING',
  },
];
